version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: orthanc2/awscli
    docker:
    - image: circleci/buildpack-deps:stretch
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Docker image
        command: docker build -t $IMAGE_NAME:latest .
workflows:
  build-master:
    jobs:
    - build:
      filters:
      branches:
        only: master
