version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: orthanc2/awscli
    docker:
    - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Docker image
        command: docker build -t $IMAGE_NAME:latest .
    - run:
        name: Archive Docker image
        command: docker save -o image.tar $IMAGE_NAME
    - persist_to_workspace:
        root: .
        paths:
        - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
    - setup_remote_docker
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Load archived Docker image
        command: docker load -i /tmp/workspace/image.tar
    - run:
        name: Calculate Tag Names
        command: |
          FULL_VERSION="$(docker run --rm orthanc2/awscli aws --version)"
          PYTHON_VERSION="$(echo "${FULL_VERSION}" | sed -e 's#^.*Python/\([^ ]*\).*$#\1#')"
          PYTHON_MINOR_VERSION="${PYTHON_VERSION%.*}"
          PYTHON_MAJOR_VERSION="${PYTHON_MINOR_VERSION%.*}"
          CLI_VERSION="$(echo "${FULL_VERSION}" | sed -e 's#^.*aws-cli/\([^ ]*\).*$#\1#')"
          CLI_MINOR_VERSION="${CLI_VERSION%.*}"
          CLI_MAJOR_VERSION="${CLI_MINOR_VERSION%.*}"

          echo "export FULL_VERSION_TAG_NAME='aws-cli-${CLI_VERSION}_python-${PYTHON_VERSION}_build-${CIRCLE_BUILD_NUM}'" >> $BASH_ENV
          echo "export MINOR_VERSION_TAG_NAME='aws-cli-${CLI_MINOR_VERSION}_python-${PYTHON_MINOR_VERSION}'" >> $BASH_ENV
          echo "export MAJOR_VERSION_TAG_NAME='aws-cli-${CLI_MAJOR_VERSION}_python-${PYTHON_MAJOR_VERSION}'" >> $BASH_ENV
    - run:
        name: Publish Docker Image to Docker Hub
        command: |
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$FULL_VERSION_TAG_NAME
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$MINOR_VERSION_TAG_NAME
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$MAJOR_VERSION_TAG_NAME

          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $IMAGE_NAME:$FULL_VERSION_TAG_NAME
          docker push $IMAGE_NAME:$MINOR_VERSION_TAG_NAME
          docker push $IMAGE_NAME:$MAJOR_VERSION_TAG_NAME
          docker push $IMAGE_NAME:latest
workflows:
  build-master:
    jobs:
    - build:
        filters:
          branches:
            only: master
    - publish-latest:
        context: docker-publishing
        requires:
        - build
        filters:
          branches:
            only: master
  weekly-build:
    triggers:
    - schedule:
        cron: 0 19 * * 6
        filters:
          branches:
            only: master
    jobs:
    - build:
        filters:
          branches:
            only: master
    - publish-latest:
        context: docker-publishing
        requires:
        - build
        filters:
          branches:
            only: master
